spring.application.name=demo

jwt.secret=f2e3d4c5b6a79808192a3b4c5d6e7f81234567890abcdef1122334455667788
jwt.expiration-ms=3600000

spring.datasource.url=jdbc:h2:file:./data/clinicmeddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


